services:
  api:
    container_name: api
    build: ./fastApiEL
    restart: always
    volumes:
      - ./fastApiEL:/app

    env_file:
      - ./fastApiEL/.env
    command: ["/fastapi_app/docker/api.sh"]
    expose:
      - 8000
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    container_name: db
    image: postgres
    volumes:
      - "db:/var/lib/postgresql/data"
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

    environment:
      - POSTGRES_HOST_AUTH_METHOD=md5
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    expose:
      - 5432
    ports:
      - "5432:5432"

volumes:
  db: