services:
  api:
    container_name: api
    build: ./fastApiEL
    restart: always
    volumes:
      - ./fastApiEL:/app

    env_file:
      - .env
    command: ["/fastapi_app/docker/api.sh"]
    expose:
      - 8000
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    container_name: db
    image: postgres:17
    volumes:
      - ./db_data:/var/lib/pgsql/data

    environment:
      - POSTGRES_HOST_AUTH_METHOD=md5
      - PGDATA=/var/lib/pgsql/data
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    
    # command: /bin/bash -c "apt-get update && apt-get install -y cron procps pkill ps && cron && docker-entrypoint.sh postgres"

    expose:
      - 5432
    ports:
      - "5432:5432"

volumes:
  db_data: