services:
  api:
    container_name: api
    build: ./fastApiEL
    restart: always
    volumes:
      - ./fastApiEL:/app
    env_file:
      - .env
    command: ["/fastapi_app/docker/api.sh"]
    expose:
      - 8000
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    container_name: db
    image: postgres:17
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_HOST_AUTH_METHOD=md5
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    expose:
      - 5432
    ports:
      - "5432:5432"

volumes:
  db_data:
