"""group_name

Revision ID: 25aa14b4c4a0
Revises: 5ac63e518bff
Create Date: 2023-10-02 22:34:42.363564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25aa14b4c4a0'
down_revision: Union[str, None] = '5ac63e518bff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('group_name', sa.INTEGER(), nullable=True))
    op.drop_column('users', 'class_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('class_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'group_name')
    # ### end Alembic commands ###
