"""chande users

Revision ID: 40e10bfd393d
Revises: 884d975267ad
Create Date: 2023-11-02 19:34:50.290533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40e10bfd393d'
down_revision: Union[str, None] = '884d975267ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'group_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('group_name', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
