"""add_jwt_token

Revision ID: 884d975267ad
Revises: 25aa14b4c4a0
Create Date: 2023-10-15 23:49:32.883190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '884d975267ad'
down_revision: Union[str, None] = '25aa14b4c4a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('jwt_token', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'jwt_token')
    # ### end Alembic commands ###
